# Aufgabe 3: Faltung
Ein wichtiger Basisalgorithmus in der Bildverarbeitung ist die diskrete Faltung
\begin{align}
 \boldsymbol{I}_A(i,j) = (\boldsymbol{I} * \boldsymbol{A})(i, j) = \sum_{h=-\lfloor \frac{m}{2} \rfloor}^{ \lfloor \frac{m}{2} \rfloor} \sum_{k=-\lfloor \frac{n}{2} \rfloor}^{ \lfloor \frac{n}{2} \rfloor} \boldsymbol{A}(h,k) \cdot \boldsymbol{I}(i-h, j-k).
 \label{eqn:lin_filt}
\end{align}

Hierbei wird eine Faltungsmaske $\boldsymbol{A} \in \mathbb{R}^{m \times n}$ verwendet und über das Eingabebild $\boldsymbol{I}$ "geschoben".
Dabei wird für jedes Pixel des Eingabebildes eine mit den korrespondierenden Einträgen der Faltungsmaske gewichtete Linearkombination der Nachbarschaftspixel berechnet.
Verschiedene Faltungsmasken haben dabei unterschiedliche Auswirkungen auf das Bild.

Eine einfache Faltungsmaske ist z.~B. der Mittelwertfilter $\boldsymbol{A}_\text{avg}$, der für eine
Größe $m=n=3$ die folgende Form hat:

\begin{equation}
 \boldsymbol{A}_\text{avg} = \frac{1}{9} \left(\begin{array}{ccc}1&1&1\\1&1&1\\1&1&1\end{array}\right).
\end{equation}

Schreiben Sie eine Python-Funktion, die diesen Mittelwertfilter auf ein Bild anwendet!
Achten Sie bei der Implementierung darauf, dass die Faltungsmaske $\boldsymbol{A}$ leicht ausgetauscht werden kann!
Überlegen Sie sich ein Vorgehen bei der Behandlung der an den Bildrändern gelegenen Pixeln!

## 0. Pfade, Pakete etc.

In [1]:
import glob
import urllib.request

%matplotlib notebook
import matplotlib.pyplot as plt

import imageio
import numpy as np

In [2]:
# image_filter = 'Bilder/*.jpg'
image_filter = 'Bilder/Aerial.jpg'

## 1. Definition der Faltungsmaske
Definieren Sie hier die Faltungsmaske `A_avg` für den Mittelwertfilter!

In [3]:
A_avg = np.array([[1/9,1/9,1/9],
                  [1/9,1/9,1/9],
                  [1/9,1/9,1/9]])
# A_avg=[[1/9]*3]*3
print(A_avg)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


## 2. Laden des Bildes

In [4]:
image_path = np.random.choice(glob.glob(image_filter))
image = imageio.imread(image_path)
print(image)

[[199 199 199 ... 230 229 232]
 [199 200 200 ... 231 229 231]
 [200 200 201 ... 232 229 229]
 ...
 [225 219 205 ... 227 213 196]
 [213 217 219 ... 215 208 211]
 [198 211 231 ... 198 202 217]]


Für diese Aufgabe ist es wichtig, das Bild im Fließkommaformat vorliegen zu haben. Konvertieren sie `image` zu einer geeigneten Repräsentation:

In [5]:
image = np.asarray(image, dtype=np.float32) / 255

## 3. Berechung der Faltung
Definieren Sie eine Funktion `ex2_convolve`, die ein Bild sowie eine Faltungsmaske übergeben bekommt und als Rückgabewert das gefaltete Bild liefert. Denken Sie an ein sinnvolles Vorgehen zur Behandlung der Bildränder.

In [6]:
def element_sum(image,filter_mask):
    res=(image*filter_mask).sum()
    if(res<0):
        res=0
    elif res>255:
        res =255
    return res

def ex2_convolve(image, filter_mask):
    convolved_image = np.zeros_like(image)
    comp_img=np.zeros_like(filter_mask)
    
    conv_rows,conv_cols = image.shape
    fil_rows,fil_cols = filter_mask.shape
    
    fil_half_rows=filter_mask.shape[0]//2
    fil_half_col=filter_mask.shape[1]//2
    img=np.pad(image,((fil_half_rows,fil_half_rows),(fil_half_col,fil_half_col)),'constant',constant_values = (0,0))
    
    for i in range(conv_rows):                     
        for j in range(conv_cols):
#             convolved_image[i][j] = element_sum(img[i-fil_half_rows:i+fil_half_rows, j-fil_half_rows:j+fil_half_rows],filter_mask)   
            convolved_image[i][j] = element_sum(img[i:i+fil_rows, j:j+fil_cols],filter_mask)*255   

    return convolved_image

Nun wird das gefaltete Bild mit Hilfe der Funktion berechnet:

In [7]:
convolved_image = ex2_convolve(image, A_avg)
convolved_image

array([[ 88.55556 , 132.88889 , 132.88889 , ..., 153.      , 153.55556 ,
        102.333336],
       [133.      , 199.66667 , 199.88889 , ..., 229.88889 , 230.22223 ,
        153.22223 ],
       [133.22223 , 200.11111 , 200.66667 , ..., 230.55556 , 230.22223 ,
        153.      ],
       ...,
       [147.33333 , 218.      , 219.77779 , ..., 205.66667 , 212.11111 ,
        138.11111 ],
       [142.55556 , 215.33333 , 218.33333 , ..., 196.33334 , 209.66667 ,
        138.55556 ],
       [ 93.22222 , 143.22223 , 146.      , ..., 127.77778 , 139.      ,
         93.111115]], dtype=float32)

## 4. Darstellung
Um die Wirksamkeit der Faltung zu überprüfen, stellen Sie `image` und `convolved_image` nebeneinander dar:

In [8]:
plt.figure('Image')

plt.subplot(1,2,1)
plt.title('original image')
plt.imshow(image, cmap='gray')

plt.subplot(1,2,2)
plt.title('convolved image')
plt.imshow(convolved_image, cmap='gray')
plt.show()

<IPython.core.display.Javascript object>